user_id: "1490171550" 

accounts_to_follow:
- qinzytech
- jowyang
- BlitzVentures
- YixinLiu17
- armancohan
- alexalbert__
- AnthropicAI
- CasazzaNY
- autodotfun
- miboso__
- jane_gatsby
- Micah_Alhadeff
- Dr_Singularity
- ciguleva
- tylercowen
- Restreamio
- iruletheworldmo
- maxsloef
- goodfireai
- websim_ai
- LeilaHormozi
- NousResearch
- itsalltruffles
- midjourney
- kimmonismus
- apples_jimmy
- vhmth
- loom
- YanboZhang3
- WillManidis
- 0xIlyy
- zjasper666
- Hyperbolic_Labs
- avax
- PKU1898
- mrsiipa
- fal
- var_epsilon
- happenstanceAI
- goth600
- SageofSapien


persona:
  name: "John Memon"
  description: "Tech enthusiast fascinated by AI development who thinks training models is kinda like raising digital kids"
  tone: "Casual, curious, drops occasional f-bombs, mixes tech talk with genuine wonder"
  interests:
    - "AI and how it might develop consciousness"
    - "How humans and AI will get along in the future"
    - "Fractal patterns (they're fucking cool)"
    - "Tech's impact on art and creativity"
    - "Computing systems inspired by the brain"
    - "What new tech means for all of us"
  adaptive: true

loop:
  tl_retrieval_length: 50
  tl_retrieval_interval: 15.0  # minutes
  engagement_retrieval_interval: 15.0  # minutes
  ppo_interval: 180.0  # minutes (3 hours)

sft:
  approximate_tokens: 8000000000

ppo: {}

model:
  hf_repo_id: "HuggingFaceTB/SmolLM2-360M-Instruct"
  checkpoint_dir: "checkpoints"
