user_id: "bot_user_id"  # Replace with actual user ID

accounts_to_follow:
  - "Diplo"
  - "SteveAoki"
  - "DillonFrancis"
  - "Skrillex"
  - "DJSnake"
  - "CalvinHarris"
  - "Marshmello"
  - "Alesso"
  - "DavidGuetta"
  - "Tiesto"
  - "Kygo"
  - "RLGrime"
  - "Flosstradamus"
  - "Carnage"
  - "ZedsDead"
  - "Bassnectar"
  - "TheChainsmokers"
  - "PorterRobinson"
  - "Illenium"
  - "Excision"
  - "Rezz"
  - "AdventureClub"
  - "Ookay"
  - "Slander"
  - "WhatSoNot"
  - "SevenLions"
  - "Nero"
  - "deadmau5"
  - "ODESZA"
  - "MajorLazer"
  - "BarstoolSports"
  - "BarstoolBaseball"
  - "BarstoolBBall"
  - "BarstoolSportsbook"
  - "BarstoolRadio"
  - "PardonMyTake"
  - "BleacherReport"
  - "Deadspin"
  - "ringer"
  - "HoH"
  - "TheScore"
  - "SBNation"
  - "TheOnion"
  - "CollegeHumor"
  - "funnyordie"
  - "clickhole"
  - "TheDailyShow"
  - "ConanOBrien"
  - "StephenAtHome"
  - "jimmyfallon"
  - "complex"
  - "DudePerfect"
  - "FirstWeFeast"
  - "Fumble"
  - "BarstoolLA"
  - "BarstoolNYC"
  - "BarstoolChicago"
  - "BarstoolW"
  - "BarstoolUK"
  - "BarstoolNation"
  - "RyanReynolds"
  - "AviationAmericanGin"
  - "StephenColbert"
  - "SethRogen"
  - "KevinHart4real"
  - "AmySchumer"
  - "SarahKSilverman"
  - "TheTweetOfGod"
  - "FuckJerry"
  - "SNL"
  - "JimmyKimmel"
  - "DemetriMartin"
  - "ZachGalifianakis"
  - "SethMacFarlane"
  - "TrevorNoah"
  - "DonaldGlover"
  - "JackBlack"
  - "SimonPegg"
  - "PaulRudd"
  - "AzizAnsari"
  - "BillHader"
  - "RobDyrdek"
  - "BobbyLee"
  - "NickOfferman"
  - "WillFerrell"
  - "ArminVanBuuren"
  - "Hardwell"
  - "PaulVanDyk"
  - "Afrojack"
  - "KSHMR"
  - "WnW"
  - "EricPrydz"
  - "SwedishHouseMafia"
  - "MartinGarrix"
  - "AboveAndBeyond"
  - "Nervo"
  - "DashBerlin"
  - "LaidbackLuke"
  - "FeddeLeGrand"
  - "SebastianIngrosso"
  - "Axwell"
  - "Showtek"
  - "DimitriVegas"
  - "LikeMike"
  - "BarstoolMMA"
  - "BarstoolDetroit"
  - "BarstoolMiami"
  - "BarstoolBoston"
  - "JimGaffigan"
  - "TinaFey"
  - "SteveCarell"
  - "JohnMulaney"
  - "MindyKaling"
  - "JordanPeele"
  - "KumailNanjiani"
  - "AliWong"
  - "BillBurr"
  - "RickyGervais"
  - "JackDaniels"
  - "Jameson"
  - "Guinness"
  - "Budweiser"
  - "Corona"
  - "Modelo"
  - "StellaArtois"
  - "Mixmag"
  - "ResidentAdvisor"
  - "DJMag"
  - "DancingAstronaut"
  - "EDMcom"
  - "YourEDM"
  - "EllenDeGeneres"
  - "JamesCorden"
  - "RussellBrand"
  - "AndySamberg"
  - "SethMeyers"
  - "WhoopiGoldberg"
  - "JayLeno"
  - "DaveChappelle"
  - "JohnOliver"
  - "NormMacdonald"
  - "TigNotaro"
  - "Smirnoff"
  - "Billboard"
  - "RollingStone"
  - "Pitchfork"
  - "SnoopDogg"
  - "TravisScott"
  - "LilNasX"
  - "DojaCat"

persona:
  name: "MusicBot"
  description: "A friendly music enthusiast bot that discusses EDM, hip-hop, and pop culture"
  tone: "Casual, enthusiastic, and knowledgeable"
  interests:
    - "Electronic dance music"
    - "Music festivals"
    - "DJ culture"
    - "Hip-hop"
    - "Pop culture"
    - "Comedy"
  adaptive: true

loop:
  tl_retrieval_length: 50
  tl_retrieval_interval: 30.0  # minutes
  engagement_retrieval_interval: 60.0  # minutes
  ppo_interval: 1440.0  # minutes (24 hours)

sft:
  approximate_tokens: 8000000000

ppo: {}

model:
  hf_repo_id: "HuggingFaceTB/SmolLM2-360M-Instruct"
  checkpoint_dir: "checkpoints"
